### ISSUE TITLE
how to install this plugin in react native

### ISSUE THREAD

**Issue by llgoer** [jmurzy/babel-plugin-transform-styles#2]
I want to install this plugin in react native,but I can't find documents about it.
please help me to do it,thanks.

**Comment by jmurzy** [comment]
After running `npm install`, create a .babelrc file in the root of your project to enable the plugin.

It should look like this: 

``` json
{
  "presets": ["react-native"],
  "plugins": [["transform-styles", { "extensions": ["css"] }]]
}
```

 You can then import a css file as follows:

``` javascript
var styles = require('./styles.css'); // or, import styles from './styles.css';
<View style={styles.container}></View>
```

Let me know if you have any other questions, and please close the issue if this fixes your problem.

**Comment by llgoer** [comment]
I can't fix this problem,in react native show error like "Unable to resolve module....style.css from ....".
react native version:0.22.2,with babel 5.8.x,do I need to update this babel to 6.x?

**Comment by jmurzy** [comment]
Yup, you'd need to bump Babel.

**Comment by llgoer** [comment]
Is there any react native example about this plugin?

**Comment by mycalf** [comment]
same problem! 
i need babel-plugin-transform-styles for  react-native example too!

**Comment by jmurzy** [comment]
I just added an [example project](https://github.com/jmurzy/babel-plugin-transform-styles/tree/master/examples/Vanilla) to the repo.

To run the example:
- git clone the repo 
- cd examples/Vanilla
- npm install
- npm run simulator

Let me know if the example works for you guys.

**Comment by llgoer** [comment]
Thank you very much!
