### ISSUE TITLE
Modify css file without triggering develop package？

### ISSUE THREAD

**Issue by mycalf** [jmurzy/babel-plugin-transform-styles#3]
css Impermissible   "  '
Modify css file without triggering develop package

**Comment by jmurzy** [comment]
> Modify css file without triggering develop package

I'm not sure I understand what you mean by that.

**Comment by mycalf** [comment]
edit for *.css files don't trigger react native debugg tool.

**Comment by jmurzy** [comment]
@mycalf the gist of it is that the React Native packager does not listen to changes in .css files. Try renaming your files to .css.js for a faster feedback loop.

🍺
